### ISSUE TITLE
Migrating to powerbi-visuals-tools 3.x got error

### ISSUE THREAD

**Issue by luojiandan** [microsoft/PowerBI-visuals-WordCloud#42]
I download the "Word Cloud" repository, Migrating to powerbi-visuals-tools 3.x, get error:
https://raw.githubusercontent.com/luojiandan/powerbi/master/Image/Error/cannot%20find%20name%20'DataViewScopeIdentity'%2020190617.png

DataViewScopeIdentity not found.
how can I change this code?

**Comment by luojiandan** [comment]
@uve could u help me!
the source code link:
https://share.weiyun.com/5wa4Njo

**Comment by helen508light** [comment]
The DataViewScopeIdentity interface is no longer supported from API 2.1, it was replaced with the data.DataRepetitionSelector interface. If you used key property of the DataViewScopeIdentity interface, you can replace it with JSON.stringify(identity)

**Comment by helen508light** [comment]
@luojiandan 
The DataRepetitionSelector interface is no longer supported, it was replaced with data.CustomVisualOpaqueIdentity interface
https://microsoft.github.io/PowerBI-visuals/docs/changelog/

**Comment by luojiandan** [comment]
@helen508light 
thank u very much.
From API2.6,I use 
`import DataViewScopeIdentity=powerbi.DataRepetitionKind.ScopeIdentity;`
It's ok!
