### ISSUE TITLE
Unlock the rows number limitation

### ISSUE THREAD

**Issue by Altheran88** [microsoft/PowerBI-visuals-WordCloud#47]
Would it be possible to modify the capabilities.json (raise to 30K) and make use of the fetchMoreData() function to unlock the amount of rows that can be analysed by the viual ?

**Comment by helen508light** [comment]
Please try dataReductionAlgorithm in capabilities.json https://microsoft.github.io/PowerBI-visuals/docs/concepts/dataviewmappings/#data-reduction-algorithm-usage

**Comment by Altheran88** [comment]
I did it, altho I had to open the pibxv archive, search the related string and modifiy .. not really an out of the box solution. I am also stuck at 30K rows analysed. I can't recode the whole thing to make use of fetchmoredata().

**Comment by uve** [comment]
Hello @Altheran88, is you set 30k rows limit in capabilites.json, the visual will receive 30k rows in both cases: initial update method and each call of fetchMoreData API.
