### ISSUE TITLE
Visual won't display in Chrome Incognito

### ISSUE THREAD

**Issue by julmoser** [microsoft/PowerBI-visuals-WordCloud#63]
We have a Power BI Report that uses the word cloud visual.
The report is published to the Power BI Report Server.
The visual is display when browsing with Edge, Edge InPrivate mode and Chrome.
But when browsing with Chrome Incognito, the visual won't display (no error message, just an empty visual container).
All other visuals are displaying properly.
Any idea where this might come from? Thanks.

**Comment by helen508light** [comment]
Has the same reason as in https://github.com/microsoft/PowerBI-visuals-AsterPlot/issues/29
So, it is duplicate
